bc:
  model:
    dims: [64,32,16]
    act: leakyrelu
    l_act: False
    norm: ln # set to False to make it false
    dropout: 0.6
    bias: False

fkd:
  fc:
    dims: [64,32,16]
    act: leakyrelu
    l_act: False
    norm: ln
    dropout: 0.2
    bias: False
  pose:
    dims: [8, 16]
    act: tanh
    l_act: True
    norm: ln
    dropout: 0.6
    bias: False

ikd:
  model:
    pose:
      dims: [64,32,16]
      act: leakyrelu
      l_act: False
      norm: ln
      dropout: 0.2
      bias: False
    fc:
      dims: [256,128,64,32,16]
      act: tanh
      l_act: False
      norm: ln
      dropout: 0.2
      bias: False